name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            animation-card.js
            hacs.json
            icons/bulb_glow_esplosivo.gif
            icons/bulb_off.png
            icons/bulb_pulse_warm.gif
            icons/fan_on.gif
            icons/fan_off.gif
